"""Agregar latitud y longitud a Partido 

Revision ID: 0d484ac74798
Revises: 58d7afa26f34
Create Date: 2025-06-19 14:34:59.053767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d484ac74798'
down_revision = '58d7afa26f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
