"""Agregar campos físicos y técnicos al usuario

Revision ID: 21e8b8bf9124
Revises: d5b6bb71c101
Create Date: 2025-07-04 23:18:53.542740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e8b8bf9124'
down_revision = 'd5b6bb71c101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion_secundaria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pie_dominante', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_fisico', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nivel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('club_actual', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dorsal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dorsal')
        batch_op.drop_column('club_actual')
        batch_op.drop_column('nivel')
        batch_op.drop_column('estado_fisico')
        batch_op.drop_column('pie_dominante')
        batch_op.drop_column('posicion_secundaria')

    # ### end Alembic commands ###
