"""Agregar campo cancelado a Partido

Revision ID: 58d7afa26f34
Revises: 
Create Date: 2025-06-19 11:21:52.511940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d7afa26f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.alter_column('puntuacion',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_column('cancelado')

    with op.batch_alter_table('calificacion', schema=None) as batch_op:
        batch_op.alter_column('puntuacion',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
